### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by curtiswilkinson** [curtiswilkinson/react-collapsible-panel#1]
- [x] Add examples
- [x] Spike React PropTypes viability given React@16
- [x] Add default styling
- [x] Add icon functionality
- [x] Add default icons 
- [x] Spike grouping component
- [ ] Add index prop to allow for tab-index to work properly
- [ ] NPM preparations
